<a href="https://colab.research.google.com/github/Rayna178/MATH311_Linear_Algebra_Projects/blob/main/Gram_Schmidt_Orthonormalization_Process.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import matplotlib.pyplot as plt
from sympy import Poly
import sympy as sym
import numpy as np
from numpy import c_

# We'll specify that x and t are variables:
x, t = sym.symbols('x, t')

ll = "loaded"

In [9]:
zz = np.matrix('1; 2; 3; 4')
zz

matrix([[1],
        [2],
        [3],
        [4]])

In [10]:
5*zz

matrix([[ 5],
        [10],
        [15],
        [20]])

In [20]:
yy = np.array([1, 2, 3, 4])
yy

array([1, 2, 3, 4])

In [21]:
yy.dot(yy)

30

In [23]:
np.sqrt(9)

3.0

# Gram-Schmidt Process:

1. Start with random vecotrs: r1, r2, r3, r4.

2. Process them in orfer, generating: u1, u2, u3, u4.

After eashc step, we'll check that out nice vectors area:
* orthogonal to previous nice vectors
* have a magnitude 1.

In [25]:
# These are the "random vectors":

r1 = np.array([3, 0, 3, 0])
print ("r1 is", r1)

r2 = np.array([3, 2, 3, 3])
print ("r2 is", r2)

r3 = np.array([-7, -4, -5, -6])
print ("r3 is", r3)

r4 = np.array([-7, -3, -11, 2])
print ("r4 is", r4)


r1 is [3 0 3 0]
r2 is [3 2 3 3]
r3 is [-7 -4 -5 -6]
r4 is [ -7  -3 -11   2]


In [ ]:
# Processing the vectors:
# Slect a random vecotr, and subract the nice pieces.
# t = r- __u1 - __u2 - __u3...
# Where the __ are the dot products pf r with the ui
# Then we'll find the magnitude of t:
# If |t| is not 0, we create u = (1/|t|)*t
# Sanity checks

In [35]:
#Process 1:
t1 = r1
print ("t1 is", t1)

# magnitude
n1 = np.sqrt(t1.dot(t1))
print("The size of t1 is",n1)

#Create u1:

u1 = (1/n1)*t1
print("u1 is", u1)

t1 is [3 0 3 0]
The size of t1 is 4.242640687119285
u1 is [0.70710678 0.         0.70710678 0.        ]


In [28]:
#Sanity Check:
print("the size of u1 is", np.sqrt(u1.dot(u1)))

the size of u1 is 1.0


In [34]:
#Process 1:
t2 = r2 - r2.dot(u1) * u1
print ("t2 is", t2)

# magnitude
n2 = np.sqrt(t2.dot(t2))
print("The size of t2 is",n2)

#Create u2:

u2 = (1/n2)*t2
print("u2 is", u2)

t2 is [-4.4408921e-16  2.0000000e+00 -4.4408921e-16  3.0000000e+00]
The size of t2 is 3.605551275463989
u2 is [-1.23168186e-16  5.54700196e-01 -1.23168186e-16  8.32050294e-01]


In [37]:
# Sanity Check
print("the size of u2 is", np.sqrt(u2.dot(u2)))
print ("the dot product of u1 and u2 is", u1.dot(u2))

the size of u2 is 1.0
the dot product of u1 and u2 is -1.741861189847285e-16
